In [3]:
import numpy as np
import pandas as pd

data = np.loadtxt("C:\\Users\\schai\\Downloads\\0000000000002417_training_boston_x_y_train.csv",delimiter = ",")

In [4]:
data

array([[-0.40784991, -0.48772236, -1.2660231 , ...,  0.41057102,
        -1.09799011, 37.9       ],
       [-0.40737368, -0.48772236,  0.24705682, ...,  0.29116915,
        -0.52047412, 21.4       ],
       [ 0.1251786 , -0.48772236,  1.01599907, ..., -3.79579542,
         0.89107588, 12.7       ],
       ...,
       [-0.40831101, -0.48772236,  0.24705682, ...,  0.33206621,
        -0.33404299, 20.8       ],
       [-0.41061997, -0.48772236, -1.15221381, ...,  0.203235  ,
        -0.74475218, 22.6       ],
       [ 0.34290895, -0.48772236,  1.01599907, ...,  0.38787479,
        -1.35871335, 50.        ]])

In [5]:
data[0:len(boston)][0:13]

NameError: name 'boston' is not defined

In [6]:
len(data)

379

In [78]:
x_train = data[0:380,0:13]

In [80]:
y_train = data[0:380, 13:14]

In [81]:
x_train

array([[-0.40784991, -0.48772236, -1.2660231 , ..., -0.30309415,
         0.41057102, -1.09799011],
       [-0.40737368, -0.48772236,  0.24705682, ...,  0.1130321 ,
         0.29116915, -0.52047412],
       [ 0.1251786 , -0.48772236,  1.01599907, ...,  0.80657583,
        -3.79579542,  0.89107588],
       ...,
       [-0.40831101, -0.48772236,  0.24705682, ...,  0.1130321 ,
         0.33206621, -0.33404299],
       [-0.41061997, -0.48772236, -1.15221381, ..., -0.71922039,
         0.203235  , -0.74475218],
       [ 0.34290895, -0.48772236,  1.01599907, ...,  0.80657583,
         0.38787479, -1.35871335]])

In [82]:
y_train


array([[37.9],
       [21.4],
       [12.7],
       [19.9],
       [22.5],
       [32.7],
       [23.2],
       [21.5],
       [20.5],
       [33.3],
       [23.1],
       [20. ],
       [50. ],
       [25. ],
       [20.2],
       [16.4],
       [22.4],
       [20.4],
       [18.4],
       [37.3],
       [23.1],
       [34.7],
       [33.1],
       [28.7],
       [15.6],
       [18.2],
       [17.2],
       [31.5],
       [26.6],
       [24.1],
       [22.3],
       [19.5],
       [36.1],
       [17.6],
       [33.4],
       [ 8.8],
       [ 9.7],
       [13.4],
       [39.8],
       [24.4],
       [17.8],
       [24.3],
       [24. ],
       [23.1],
       [13.1],
       [16.7],
       [22.8],
       [27.5],
       [14.6],
       [13.4],
       [11. ],
       [19.4],
       [15. ],
       [44.8],
       [29.6],
       [12.3],
       [24.6],
       [10.9],
       [28. ],
       [30.8],
       [15.4],
       [18. ],
       [35.2],
       [11.5],
       [19.5],
       [24.8],
       [22

In [10]:
y_train

array([[37.9],
       [21.4],
       [12.7],
       [19.9],
       [22.5],
       [32.7],
       [23.2],
       [21.5],
       [20.5],
       [33.3],
       [23.1],
       [20. ],
       [50. ],
       [25. ],
       [20.2],
       [16.4],
       [22.4],
       [20.4],
       [18.4],
       [37.3],
       [23.1],
       [34.7],
       [33.1],
       [28.7],
       [15.6],
       [18.2],
       [17.2],
       [31.5],
       [26.6],
       [24.1],
       [22.3],
       [19.5],
       [36.1],
       [17.6],
       [33.4],
       [ 8.8],
       [ 9.7],
       [13.4],
       [39.8],
       [24.4],
       [17.8],
       [24.3],
       [24. ],
       [23.1],
       [13.1],
       [16.7],
       [22.8],
       [27.5],
       [14.6],
       [13.4],
       [11. ],
       [19.4],
       [15. ],
       [44.8],
       [29.6],
       [12.3],
       [24.6],
       [10.9],
       [28. ],
       [30.8],
       [15.4],
       [18. ],
       [35.2],
       [11.5],
       [19.5],
       [24.8],
       [22

In [11]:
len(x_train)

379

In [12]:
len(x_train[0])

13

In [13]:
x_train[[2]]

array([[ 0.1251786 , -0.48772236,  1.01599907, -0.27259857,  1.36749033,
        -0.43969866,  0.68721157, -0.57730857,  1.66124525,  1.53092646,
         0.80657583, -3.79579542,  0.89107588]])

In [14]:
x_train[2]

array([ 0.1251786 , -0.48772236,  1.01599907, -0.27259857,  1.36749033,
       -0.43969866,  0.68721157, -0.57730857,  1.66124525,  1.53092646,
        0.80657583, -3.79579542,  0.89107588])

In [15]:
x_train[1,2]

0.24705682

In [16]:
def run(x,y):
    lr = 0.001
    n = 1000
    Gradient_Descent(x,y,lr,n)

In [19]:

def step_gradient(points, learning_rate, m , c):
    new_m = np.zeros(points.shape[1] - 1)
    new_c = 0
    M = len(points)
    for j in range(len(m)-1):
        m_slope = 0
        c_slope = 0
        for i in range(M):
            x = points[i, j]
            y = points[i, -1]
            m_slope += (-2/M)* (y - m[j] * x - c)*x
            c_slope += (-2/M)* (y - m[j] * x - c)
            
        new_m[j] = m[j] - learning_rate * m_slope
        new_c = c - learning_rate * c_slope
    return new_m, new_c

def gd(points, learning_rate, num_iterations):
    m = np.zeros(points.shape[1] - 1)     
    c = 0     
    for i in range(num_iterations):
        m, c = step_gradient(points, learning_rate, m , c)
        print(i, " Cost: ", cost(points, m, c))
    return m, c

def cost(points, m, c):
    total_cost = 0
    M = len(points)
    for j in range(len(m)):
        for i in range(M):
            x = points[i, j]
            y = points[i, -1]
            total_cost += (1/M)*((y - m[j]*x - c)**2)
    return total_cost

def run():
    learning_rate = 0.05
    num_iterations = 50
    m, c = gd(data, learning_rate, num_iterations)
    print("Final m :", m)
    print("Final c :", c)
    return m,c

In [20]:
run()

0  Cost:  6496.813904036528
1  Cost:  5449.821177386607
2  Cost:  4601.205804861045
3  Cost:  3913.3636603444575
4  Cost:  3355.8219605381064
5  Cost:  2903.8862536548745
6  Cost:  2537.544228946031
7  Cost:  2240.577575830052
8  Cost:  1999.8423877438438
9  Cost:  1804.6861107264613
10  Cost:  1646.4751151902485
11  Cost:  1518.2118925965763
12  Cost:  1414.2248664847318
13  Cost:  1329.9170373646168
14  Cost:  1261.5622974068292
15  Cost:  1206.1403702837163
16  Cost:  1161.2030483866092
17  Cost:  1124.7657904632827
18  Cost:  1095.2198694362116
19  Cost:  1071.261172951359
20  Cost:  1051.8324987064987
21  Cost:  1036.0767857311876
22  Cost:  1023.2992081973892
23  Cost:  1012.9364516241592
24  Cost:  1004.5318099931809
25  Cost:  997.7150004831923
26  Cost:  992.18580173759
27  Cost:  987.7007910992212
28  Cost:  984.0625936104077
29  Cost:  981.1111668881614
30  Cost:  978.7167361863243
31  Cost:  976.7740670539288
32  Cost:  975.1978222370099
33  Cost:  973.9187974782584
34  Cos

(array([-3.22872267,  2.94331151, -4.42226616,  1.57203964, -3.87850677,
         6.29424094, -3.35390555,  2.1252218 , -3.22086449, -4.07160221,
        -4.60618582,  3.02576403,  0.        ]),
 22.53915491800462)

In [22]:
m,c = run()

0  Cost:  6496.813904036528
1  Cost:  5449.821177386607
2  Cost:  4601.205804861045
3  Cost:  3913.3636603444575
4  Cost:  3355.8219605381064
5  Cost:  2903.8862536548745
6  Cost:  2537.544228946031
7  Cost:  2240.577575830052
8  Cost:  1999.8423877438438
9  Cost:  1804.6861107264613
10  Cost:  1646.4751151902485
11  Cost:  1518.2118925965763
12  Cost:  1414.2248664847318
13  Cost:  1329.9170373646168
14  Cost:  1261.5622974068292
15  Cost:  1206.1403702837163
16  Cost:  1161.2030483866092
17  Cost:  1124.7657904632827
18  Cost:  1095.2198694362116
19  Cost:  1071.261172951359
20  Cost:  1051.8324987064987
21  Cost:  1036.0767857311876
22  Cost:  1023.2992081973892
23  Cost:  1012.9364516241592
24  Cost:  1004.5318099931809
25  Cost:  997.7150004831923
26  Cost:  992.18580173759
27  Cost:  987.7007910992212
28  Cost:  984.0625936104077
29  Cost:  981.1111668881614
30  Cost:  978.7167361863243
31  Cost:  976.7740670539288
32  Cost:  975.1978222370099
33  Cost:  973.9187974782584
34  Cos

In [24]:
print(m)

[-3.22872267  2.94331151 -4.42226616  1.57203964 -3.87850677  6.29424094
 -3.35390555  2.1252218  -3.22086449 -4.07160221 -4.60618582  3.02576403
  0.        ]


In [25]:
print(c)

22.53915491800462


In [34]:
## Predicting the outputs

In [28]:
x_test = np.loadtxt("C:\\Users\\schai\\Downloads\\0000000000002417_test_boston_x_test.csv",delimiter = ",")

In [29]:
x_test

array([[ 2.91816626, -0.48772236,  1.01599907, ...,  0.80657583,
        -1.59755122,  1.04106182],
       [-0.40339151, -0.48772236,  0.40609801, ..., -1.13534664,
         0.44105193, -0.89473812],
       [-0.4131781 , -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.50084979],
       ...,
       [-0.41001449,  2.08745172, -1.37837329, ..., -0.0719129 ,
         0.39094481, -0.68167397],
       [-0.40317611, -0.48772236, -0.37597609, ...,  1.13022958,
         0.34007019,  0.20142086],
       [-0.13356344, -0.48772236,  1.2319449 , ..., -1.73641788,
        -2.93893082,  0.48877712]])

In [30]:
x_test.shape

(127, 13)

In [31]:
len(x_test[0])

13

In [45]:
def predict(x):
    y = []
    for i in range(len(x)):
        y_pred = 0
        for j in range(len(x[0])):
            y_pred += m[j]*x[i][j]
        y.append(y_pred+c)
    return y
            

In [46]:
y_pred = predict(x_test)

In [47]:
y_pred

[-30.896114846958078,
 45.8117282135986,
 19.267115059006684,
 49.101027368984845,
 22.955782730880962,
 -8.474752066480363,
 45.298556134050585,
 38.144638839120255,
 19.358115680417345,
 31.233424695248246,
 36.5313747782736,
 19.36571352223024,
 38.38519129768203,
 29.786891216797144,
 45.45507050782156,
 48.807837179951875,
 39.148068573139085,
 38.67972185082415,
 46.33338845814319,
 42.0468486962624,
 23.79420689612043,
 15.073691365774469,
 24.9946767983274,
 57.637729586483914,
 70.79337862026863,
 -14.181384897790345,
 27.751078937933983,
 54.2276459470293,
 30.24000168878553,
 41.95829512472292,
 20.566263509453808,
 35.34733955242999,
 24.438645576550016,
 38.232519432457465,
 -14.09190356092084,
 35.86619747185355,
 44.955229060214975,
 18.429670332428298,
 45.0939012052512,
 -24.04745565171949,
 -34.240398739696985,
 51.975107971477,
 63.233442382107604,
 5.668962600389502,
 -3.879045919635299,
 -34.80033251609311,
 52.07484470341194,
 29.135865152068384,
 72.6148682758456

In [54]:
pred_file_path = "C:\\Users\\schai\\Downloads\\Output.csv"
np.savetxt(pred_file_path ,y_pred, fmt='%.5f')

In [39]:
y_pred.shape

AttributeError: 'NoneType' object has no attribute 'shape'

In [55]:
from sklearn.ensemble import GradientBoostingClassifier

In [59]:
df = pd.DataFrame(data)

In [60]:
df

0         1         2         3         4         5         6   \
0   -0.407850 -0.487722 -1.266023 -0.272599 -0.576134  1.239974  0.840122   
1   -0.407374 -0.487722  0.247057 -0.272599 -1.016689  0.001946 -0.838337   
2    0.125179 -0.487722  1.015999 -0.272599  1.367490 -0.439699  0.687212   
3    0.028304 -0.487722  1.015999 -0.272599  1.859875 -0.047918  0.801005   
4   -0.412408 -0.487722 -0.969827 -0.272599 -0.913029 -0.384137 -0.834781   
..        ...       ...       ...       ...       ...       ...       ...   
374 -0.204929 -0.487722  1.231945  3.668398  0.434551  2.161728  1.053485   
375  0.231398 -0.487722  1.015999 -0.272599  1.367490  0.215644  0.687212   
376 -0.408311 -0.487722  0.247057 -0.272599 -1.016689 -0.206055 -0.809889   
377 -0.410620 -0.487722 -1.152214 -0.272599 -0.818007  0.068904 -1.826921   
378  0.342909 -0.487722  1.015999  3.668398  0.659147  1.041946  1.028593   

           7         8         9         10        11        12    13  
0   -0.520264 -0.752922 -1.278354 -0.303094  0.410571 -1.097990  37.9  
1    0.336351 -0.523001 -0.060801  0.113032  0.291169 -0.520474  21.4  
2   -0.577309  1.661245  1.530926  0.806576 -3.795795  0.891076  12.7  
3   -0.712836  1.661245  1.530926  0.806576 -0.066050  0.215438  19.9  
4    0.300508 -0.752922 -0.957633  0.020560  0.431074  0.029007  22.5  
..        ...       ...       ...       ...       ...       ...   ...  
374 -0.833960 -0.523001 -0.031105 -1.736418  0.361122 -1.504494  50.0  
375 -0.703186  1.661245  1.530926  0.806576 -2.812183  0.499991  14.3  
376  0.140451 -0.523001 -0.060801  0.113032  0.332066 -0.334043  20.8  
377  0.674814 -0.637962  0.129256 -0.719220  0.203235 -0.744752  22.6  
378 -1.232462  1.661245  1.530926  0.806576  0.387875 -1.358713  50.0  

[379 rows x 14 columns]

In [63]:
x_train = df.drop(13,axis = 1)

In [64]:
x_train

0         1         2         3         4         5         6   \
0   -0.407850 -0.487722 -1.266023 -0.272599 -0.576134  1.239974  0.840122   
1   -0.407374 -0.487722  0.247057 -0.272599 -1.016689  0.001946 -0.838337   
2    0.125179 -0.487722  1.015999 -0.272599  1.367490 -0.439699  0.687212   
3    0.028304 -0.487722  1.015999 -0.272599  1.859875 -0.047918  0.801005   
4   -0.412408 -0.487722 -0.969827 -0.272599 -0.913029 -0.384137 -0.834781   
..        ...       ...       ...       ...       ...       ...       ...   
374 -0.204929 -0.487722  1.231945  3.668398  0.434551  2.161728  1.053485   
375  0.231398 -0.487722  1.015999 -0.272599  1.367490  0.215644  0.687212   
376 -0.408311 -0.487722  0.247057 -0.272599 -1.016689 -0.206055 -0.809889   
377 -0.410620 -0.487722 -1.152214 -0.272599 -0.818007  0.068904 -1.826921   
378  0.342909 -0.487722  1.015999  3.668398  0.659147  1.041946  1.028593   

           7         8         9         10        11        12  
0   -0.520264 -0.752922 -1.278354 -0.303094  0.410571 -1.097990  
1    0.336351 -0.523001 -0.060801  0.113032  0.291169 -0.520474  
2   -0.577309  1.661245  1.530926  0.806576 -3.795795  0.891076  
3   -0.712836  1.661245  1.530926  0.806576 -0.066050  0.215438  
4    0.300508 -0.752922 -0.957633  0.020560  0.431074  0.029007  
..        ...       ...       ...       ...       ...       ...  
374 -0.833960 -0.523001 -0.031105 -1.736418  0.361122 -1.504494  
375 -0.703186  1.661245  1.530926  0.806576 -2.812183  0.499991  
376  0.140451 -0.523001 -0.060801  0.113032  0.332066 -0.334043  
377  0.674814 -0.637962  0.129256 -0.719220  0.203235 -0.744752  
378 -1.232462  1.661245  1.530926  0.806576  0.387875 -1.358713  

[379 rows x 13 columns]

In [67]:
y_train = df[13]

In [69]:
x_train

0         1         2         3         4         5         6   \
0   -0.407850 -0.487722 -1.266023 -0.272599 -0.576134  1.239974  0.840122   
1   -0.407374 -0.487722  0.247057 -0.272599 -1.016689  0.001946 -0.838337   
2    0.125179 -0.487722  1.015999 -0.272599  1.367490 -0.439699  0.687212   
3    0.028304 -0.487722  1.015999 -0.272599  1.859875 -0.047918  0.801005   
4   -0.412408 -0.487722 -0.969827 -0.272599 -0.913029 -0.384137 -0.834781   
..        ...       ...       ...       ...       ...       ...       ...   
374 -0.204929 -0.487722  1.231945  3.668398  0.434551  2.161728  1.053485   
375  0.231398 -0.487722  1.015999 -0.272599  1.367490  0.215644  0.687212   
376 -0.408311 -0.487722  0.247057 -0.272599 -1.016689 -0.206055 -0.809889   
377 -0.410620 -0.487722 -1.152214 -0.272599 -0.818007  0.068904 -1.826921   
378  0.342909 -0.487722  1.015999  3.668398  0.659147  1.041946  1.028593   

           7         8         9         10        11        12  
0   -0.520264 -0.752922 -1.278354 -0.303094  0.410571 -1.097990  
1    0.336351 -0.523001 -0.060801  0.113032  0.291169 -0.520474  
2   -0.577309  1.661245  1.530926  0.806576 -3.795795  0.891076  
3   -0.712836  1.661245  1.530926  0.806576 -0.066050  0.215438  
4    0.300508 -0.752922 -0.957633  0.020560  0.431074  0.029007  
..        ...       ...       ...       ...       ...       ...  
374 -0.833960 -0.523001 -0.031105 -1.736418  0.361122 -1.504494  
375 -0.703186  1.661245  1.530926  0.806576 -2.812183  0.499991  
376  0.140451 -0.523001 -0.060801  0.113032  0.332066 -0.334043  
377  0.674814 -0.637962  0.129256 -0.719220  0.203235 -0.744752  
378 -1.232462  1.661245  1.530926  0.806576  0.387875 -1.358713  

[379 rows x 13 columns]

In [70]:
y_train

0      37.9
1      21.4
2      12.7
3      19.9
4      22.5
       ... 
374    50.0
375    14.3
376    20.8
377    22.6
378    50.0
Name: 13, Length: 379, dtype: float64

In [86]:
alg = GradientBoostingClassifier()
x_train = data[:300,:-1]
y_train = data[:300,-1]
alg.fit(x_train,y_train)

ValueError: Unknown label type: 'continuous'

In [83]:
alg.fit(x_train,y_train)

C:\Users\schai\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


ValueError: Unknown label type: 'continuous'