In [2]:
from sklearn.linear_model import LinearRegression
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split

In [4]:
iris = datasets.load_iris()

In [6]:
x_train,x_test,y_train,y_test = train_test_split(iris.data, iris.target)

In [8]:
print(x_train.shape, y_train.shape , x_test.shape, y_test.shape)


(112, 4) (112,) (38, 4) (38,)


In [12]:
from sklearn.linear_model import LogisticRegression

In [14]:
clf = LogisticRegression()

In [16]:
clf.fit(x_train,y_train)

LogisticRegression()

In [19]:
y_pred = clf.predict(x_test)

In [24]:
y_pred

array([2, 0, 2, 2, 1, 0, 2, 0, 0, 0, 2, 2, 0, 0, 1, 0, 1, 0, 2, 0, 2, 1,
       0, 2, 2, 1, 2, 0, 1, 1, 0, 0, 1, 0, 2, 2, 0, 2])

In [25]:
y_train_pred = clf.predict(x_train)

In [22]:
from sklearn.metrics import confusion_matrix

In [29]:
confusion_matrix(y_train,y_train_pred)

array([[34,  0,  0],
       [ 0, 41,  1],
       [ 0,  1, 35]], dtype=int64)

In [30]:
confusion_matrix(y_test,y_pred)

array([[16,  0,  0],
       [ 0,  7,  1],
       [ 0,  1, 13]], dtype=int64)