In [1]:
## FORWARD PROPOGATION 

In [2]:
import numpy as np

In [10]:
x = np.array([[0,0],[0,1], [1,0], [1,1]])
y = np.array([[0,0,0,1]]).T

In [12]:
print(x.shape,y.shape)

(4, 2) (4, 1)


In [13]:
def sigmoid(z):
    return 1/(1+np.exp(-z))


In [21]:
weights = 2 * np.random.random((2,1)) - 1

In [22]:
weights

array([[ 0.89106079],
       [-0.58595709]])

Weights can be negative

In [25]:
bias = 2*np.random.random((1,1)) - 1

In [27]:
bias

array([[-0.62006117]])

There can be more than one bias

## Forward Propogation without hidden layers

In [28]:
output0 = x
output = sigmoid(np.dot(output0, weights) + bias)

In [30]:
output

array([[0.34976754],
       [0.23040633],
       [0.56733829],
       [0.42190514]])

## Forward Propogation with hidden layers

In [40]:
wh = 2*np.random.random((2,2))-1
bh = 2*np.random.random((1,2)) - 1
wh

array([[ 0.54769838,  0.16956782],
       [-0.83749141,  0.89516927]])

In [45]:
wo = 2*np.random.random((2,1)) - 1
bo = 2*np.random.random((1,1))-1

In [48]:
output0 = x
outputHidden = sigmoid(np.dot(output0,wh) + bh)

In [50]:
outputHidden

array([[0.68363085, 0.59881954],
       [0.48326049, 0.78511348],
       [0.7888832 , 0.63879011],
       [0.61791677, 0.81233983]])