In [1]:
import pandas as pd
import numpy as np

data = np.loadtxt("C:\\Users\\schai\\Downloads\\Coding Ninjas\\PowerPlant\\Powercycle_Train.csv",delimiter = ",")


In [2]:
data

array([[   8.58,   38.38, 1021.03,   84.37,  482.26],
       [  21.79,   58.2 , 1017.21,   66.74,  446.94],
       [  16.64,   48.92, 1011.55,   78.76,  452.56],
       ...,
       [  29.8 ,   69.34, 1009.36,   64.74,  437.65],
       [  16.37,   54.3 , 1017.94,   63.63,  459.97],
       [  30.11,   62.04, 1010.69,   47.96,  444.42]])

In [3]:
df = pd.DataFrame(data)

In [4]:
df = pd.read_csv("C:\\Users\\schai\\Downloads\\Coding Ninjas\\PowerPlant\\Powercycle_Train.csv")

In [5]:
df

# T      V       AP     RH      EP
0      8.58  38.38  1021.03  84.37  482.26
1     21.79  58.20  1017.21  66.74  446.94
2     16.64  48.92  1011.55  78.76  452.56
3     31.38  71.32  1009.17  60.42  433.44
4      9.20  40.03  1017.05  92.46  480.38
...     ...    ...      ...    ...     ...
7171   9.32  37.73  1022.14  79.49  477.91
7172  11.20  41.38  1021.65  61.89  476.87
7173  29.80  69.34  1009.36  64.74  437.65
7174  16.37  54.30  1017.94  63.63  459.97
7175  30.11  62.04  1010.69  47.96  444.42

[7176 rows x 5 columns]

In [6]:
data = df.copy()

Features consist of hourly average ambient variables 
- Temperature (T) in the range 1.81°C and 37.11°C,
- Ambient Pressure (AP) in the range 992.89-1033.30 milibar,
- Relative Humidity (RH) in the range 25.56% to 100.16%
- Exhaust Vacuum (V) in the range 25.36-81.56 cm Hg
- Net hourly electrical energy output (EP) 420.26-495.76 MW

In [7]:
df.columns = ["T","AP","RH","V","EP"]

In [8]:
df

T     AP       RH      V      EP
0      8.58  38.38  1021.03  84.37  482.26
1     21.79  58.20  1017.21  66.74  446.94
2     16.64  48.92  1011.55  78.76  452.56
3     31.38  71.32  1009.17  60.42  433.44
4      9.20  40.03  1017.05  92.46  480.38
...     ...    ...      ...    ...     ...
7171   9.32  37.73  1022.14  79.49  477.91
7172  11.20  41.38  1021.65  61.89  476.87
7173  29.80  69.34  1009.36  64.74  437.65
7174  16.37  54.30  1017.94  63.63  459.97
7175  30.11  62.04  1010.69  47.96  444.42

[7176 rows x 5 columns]

In [9]:
len(data)

7176

In [11]:
x_train = df.drop('EP',axis = 1)

In [12]:
x_train

T     AP       RH      V
0      8.58  38.38  1021.03  84.37
1     21.79  58.20  1017.21  66.74
2     16.64  48.92  1011.55  78.76
3     31.38  71.32  1009.17  60.42
4      9.20  40.03  1017.05  92.46
...     ...    ...      ...    ...
7171   9.32  37.73  1022.14  79.49
7172  11.20  41.38  1021.65  61.89
7173  29.80  69.34  1009.36  64.74
7174  16.37  54.30  1017.94  63.63
7175  30.11  62.04  1010.69  47.96

[7176 rows x 4 columns]

In [13]:
y_train = df['EP']

In [19]:
y_train

0       482.26
1       446.94
2       452.56
3       433.44
4       480.38
         ...  
7171    477.91
7172    476.87
7173    437.65
7174    459.97
7175    444.42
Name: EP, Length: 7176, dtype: float64

In [21]:
from sklearn import preprocessing
scaler = preprocessing.StandardScaler()

x = scaler.fit_transform(x_train)

In [22]:
x

array([[-1.47827466e+00, -1.24764165e+00,  1.30221067e+00,
         7.58624590e-01],
       [ 2.89012041e-01,  3.06797549e-01,  6.61749044e-01,
        -4.46921842e-01],
       [-3.99975582e-01, -4.21012529e-01, -2.87207194e-01,
         3.75010552e-01],
       ...,
       [ 1.36062192e+00,  1.18048335e+00, -6.54382840e-01,
        -5.83682640e-01],
       [-4.36097263e-01,  9.29089763e-04,  7.84140927e-01,
        -6.59584883e-01],
       [ 1.40209496e+00,  6.07960340e-01, -4.31394890e-01,
        -1.73110573e+00]])

In [23]:
from sklearn.linear_model import SGDRegressor

In [24]:
alg = SGDRegressor()

In [25]:
alg.fit(x_train,y_train)

SGDRegressor()

In [26]:
alg.score(x_train,y_train)

-1.1211386187389732e+26

In [28]:
x_test = np.loadtxt("C:\\Users\\schai\\Downloads\\Coding Ninjas\\PowerPlant\\Powercycle_Test.csv",delimiter = ",")


In [40]:
x_test

array([[  11.95,   42.03, 1017.58,   90.89],
       [  12.07,   38.25, 1012.67,   81.66],
       [  26.91,   74.99, 1005.64,   78.98],
       ...,
       [  24.32,   66.25, 1009.09,   91.89],
       [  23.49,   42.8 , 1013.96,   65.31],
       [  21.76,   60.27, 1018.96,   85.06]])

In [57]:
y_pred = alg.predict(x_test)

In [58]:
y_pred

array([-1.71892528e+14, -1.68477336e+14, -2.48079126e+14, ...,
       -2.27076795e+14, -1.98201021e+14, -2.17094581e+14])

In [59]:
def step_gradient(points, learning_rate, m , c):
    new_m = np.zeros(points.shape[1] - 1)
    new_c = 0
    M = len(points)
    for j in range(len(m)-1):
        m_slope = 0
        c_slope = 0
        for i in range(M):
            x = points[i, j]
            y = points[i, -1]
            m_slope += (-2/M)* (y - m[j] * x - c)*x
            c_slope += (-2/M)* (y - m[j] * x - c)
            
        new_m[j] = m[j] - learning_rate * m_slope
        new_c = c - learning_rate * c_slope
    return new_m, new_c

def gd(points, learning_rate, num_iterations):
    m = np.zeros(points.shape[1] - 1)     
    c = 0     
    for i in range(num_iterations):
        m, c = step_gradient(points, learning_rate, m , c)
        print(i, " Cost: ", cost(points, m, c))
    return m, c

def cost(points, m, c):
    total_cost = 0
    M = len(points)
    for j in range(len(m)):
        for i in range(M):
            x = points[i, j]
            y = points[i, -1]
            total_cost += (1/M)*((y - m[j]*x - c)**2)
    return total_cost

def run():
    learning_rate = 0.05
    num_iterations = 50
    m, c = gd(data, learning_rate, num_iterations)
    print("Final m :", m)
    print("Final c :", c)
    return m,c

In [ ]:
def run(x,y):
    lr = 0.01
    n = 1000
    gd(data,lr,n)

0  Cost:  870123729154.0366
1  Cost:  3.66551416061643e+18
2  Cost:  1.5441573034359701e+25
3  Cost:  6.5050131397536e+31
4  Cost:  2.7403423119011664e+38
5  Cost:  1.1544136537563505e+45
6  Cost:  4.863154789791471e+51
7  Cost:  2.0486828471333877e+58
8  Cost:  8.630408838618425e+64
9  Cost:  3.635699729019723e+71
10  Cost:  1.531597490543717e+78
11  Cost:  6.452102890444967e+84
12  Cost:  2.7180530110498782e+91
13  Cost:  1.1450239241872872e+98
14  Cost:  4.823599030744524e+104
15  Cost:  2.0320193419463567e+111
16  Cost:  8.560211119801362e+117
17  Cost:  3.606127801194178e+124
18  Cost:  1.519139836220184e+131
19  Cost:  6.399623000679351e+137
20  Cost:  2.6959450061375088e+144
21  Cost:  1.1357105684735257e+151
22  Cost:  4.784365008952566e+157
23  Cost:  2.0154913737974133e+164
24  Cost:  8.490584372744345e+170
25  Cost:  3.5767964044850063e+177
26  Cost:  1.5067835095314516e+184
27  Cost:  6.347569970013067e+190
28  Cost:  2.674016822545429e+197
29  Cost:  1.1264729654080866e+20

C:\Users\schai\AppData\Local\Temp/ipykernel_18784/4224282149.py:33: RuntimeWarning: overflow encountered in double_scalars
  total_cost += (1/M)*((y - m[j]*x - c)**2)


46  Cost:  inf
47  Cost:  inf
48  Cost:  inf
49  Cost:  inf
50  Cost:  inf
51  Cost:  inf
52  Cost:  inf
53  Cost:  inf
54  Cost:  inf
55  Cost:  inf
56  Cost:  inf
57  Cost:  inf
58  Cost:  inf
59  Cost:  inf
60  Cost:  inf
61  Cost:  inf
62  Cost:  inf
63  Cost:  inf
64  Cost:  inf
65  Cost:  inf
66  Cost:  inf
67  Cost:  inf
68  Cost:  inf
69  Cost:  inf
70  Cost:  inf
71  Cost:  inf
72  Cost:  inf
73  Cost:  inf
74  Cost:  inf
75  Cost:  inf
76  Cost:  inf
77  Cost:  inf
78  Cost:  inf
79  Cost:  inf
80  Cost:  inf
81  Cost:  inf
82  Cost:  inf
83  Cost:  inf
84  Cost:  inf
85  Cost:  inf
86  Cost:  inf
87  Cost:  inf
88  Cost:  inf
89  Cost:  inf
90  Cost:  inf
91  Cost:  inf


C:\Users\schai\AppData\Local\Temp/ipykernel_18784/4224282149.py:11: RuntimeWarning: overflow encountered in double_scalars
  m_slope += (-2/M)* (y - m[j] * x - c)*x


92  Cost:  inf
93  Cost:  nan


C:\Users\schai\AppData\Local\Temp/ipykernel_18784/4224282149.py:14: RuntimeWarning: invalid value encountered in double_scalars
  new_m[j] = m[j] - learning_rate * m_slope
C:\Users\schai\AppData\Local\Temp/ipykernel_18784/4224282149.py:15: RuntimeWarning: invalid value encountered in double_scalars
  new_c = c - learning_rate * c_slope


94  Cost:  nan
95  Cost:  nan
96  Cost:  nan
97  Cost:  nan
98  Cost:  nan
99  Cost:  nan
100  Cost:  nan
101  Cost:  nan
102  Cost:  nan
103  Cost:  nan
104  Cost:  nan
105  Cost:  nan
106  Cost:  nan
107  Cost:  nan
108  Cost:  nan
109  Cost:  nan
110  Cost:  nan
111  Cost:  nan
112  Cost:  nan
113  Cost:  nan
114  Cost:  nan
115  Cost:  nan
116  Cost:  nan
117  Cost:  nan
118  Cost:  nan
119  Cost:  nan
120  Cost:  nan
121  Cost:  nan
122  Cost:  nan
123  Cost:  nan
124  Cost:  nan
125  Cost:  nan
126  Cost:  nan
127  Cost:  nan
128  Cost:  nan
129  Cost:  nan
130  Cost:  nan
131  Cost:  nan
132  Cost:  nan
133  Cost:  nan
134  Cost:  nan
135  Cost:  nan
136  Cost:  nan
137  Cost:  nan
138  Cost:  nan
139  Cost:  nan
140  Cost:  nan
141  Cost:  nan
142  Cost:  nan
143  Cost:  nan
144  Cost:  nan
145  Cost:  nan
146  Cost:  nan
147  Cost:  nan
148  Cost:  nan
149  Cost:  nan
150  Cost:  nan
151  Cost:  nan
152  Cost:  nan
153  Cost:  nan
154  Cost:  nan
155  Cost:  nan
156  Cost:  na

609  Cost:  nan
610  Cost:  nan
611  Cost:  nan
612  Cost:  nan
613  Cost:  nan
614  Cost:  nan
615  Cost:  nan
616  Cost:  nan
617  Cost:  nan
618  Cost:  nan
619  Cost:  nan
620  Cost:  nan
621  Cost:  nan
622  Cost:  nan
623  Cost:  nan
624  Cost:  nan
625  Cost:  nan
626  Cost:  nan
627  Cost:  nan
628  Cost:  nan
629  Cost:  nan
630  Cost:  nan
631  Cost:  nan
632  Cost:  nan
633  Cost:  nan
634  Cost:  nan
635  Cost:  nan
636  Cost:  nan
637  Cost:  nan
638  Cost:  nan
639  Cost:  nan
640  Cost:  nan
641  Cost:  nan
642  Cost:  nan
643  Cost:  nan
644  Cost:  nan
645  Cost:  nan
646  Cost:  nan
647  Cost:  nan
648  Cost:  nan
649  Cost:  nan
650  Cost:  nan
651  Cost:  nan
652  Cost:  nan
653  Cost:  nan
654  Cost:  nan
655  Cost:  nan
656  Cost:  nan
657  Cost:  nan
658  Cost:  nan
659  Cost:  nan
660  Cost:  nan
661  Cost:  nan
662  Cost:  nan
663  Cost:  nan
664  Cost:  nan
665  Cost:  nan
666  Cost:  nan
667  Cost:  nan
668  Cost:  nan
669  Cost:  nan
670  Cost:  nan
671  Cos

TypeError: cannot unpack non-iterable NoneType object

In [46]:
y_pred.shape

(2392,)

In [47]:
pred_file_path = "C:\\Users\\schai\\Downloads\\PowerCycle_Output.csv"
np.savetxt(pred_file_path ,y_pred, fmt='%.5f')